name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  BRANCH_NAME:
    description: "Who to greet"
    required: true
    default: "DEFAULT"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"