name: A workflow for my Hello World file
on: pull_request

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          BRANCH_NAME: github.event.pull_request.head.ref
          MY_NAME: "JAMES"